spring:
  application:
    name: BarbeariaAPi
  datasource:
    url: jdbc:postgresql:\\localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    proprieties:
      hibernate.format_sql: true